
#app:
  #url: http://localhost:7777
#cognito:
 # rooturl: https://focuswts.auth.ca-central-1.amazoncognito.com
server:
  port: 8080
spring:

  datasource:
    password: 1337
    url: jdbc:mysql://localhost:9090/angularSpringAWS?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: dev
  jpa:
    hibernate:
      ddl-auto: update

